from oracles.cryptohack.cryptohackpasswordaes import CryptohackPasswordAESOracle
from oracles.cryptohack.cryptohackprosign3 import Prosign3
from oracles.cryptohack.cryptohackprosign3signature import Prosign3Signature
